# Generated by GuardOps init
# Replace this with your application's actual Dockerfile

FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app

# Install dependencies first (separate layer for Docker cache efficiency)
# If only requirements.txt changes, Docker rebuilds from here.
# If only source code changes, this layer is cached.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || true

# Copy application source code
COPY . .

# Run as non-root user for security (see Phase 3 for full security hardening)
RUN useradd --no-create-home --shell /bin/false appuser
USER appuser

# Expose the port your app listens on
EXPOSE 8080

# Healthcheck: Docker will run this every 30s to check if container is healthy
# Replace /healthz with your actual health endpoint
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/healthz')" || exit 1

# The command that runs when the container starts
# Replace this with your actual startup command
CMD ["python", "-m", "http.server", "8080"]
