project:
  name: test-app
  description: ''
  cloud: aws
docker:
  dockerfile: Dockerfile
  context: .
  registry: "236796665744.dkr.ecr.ap-south-1.amazonaws.com"
  image_name: test-app
kubernetes:
  namespace: default
  cluster_context: k3d-guardops-local
  deployment_name: test-app
security:
  fail_on_severity: HIGH
  tools:
    semgrep: true
    bandit: true
    trivy: true
    sonarqube: false
    owasp_zap: true
monitoring:
  grafana_url: ''
  prometheus_url: ''
  loki_url: 'http://localhost:3100'

